### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by AndKe** [comment]
The current SC2 documentation downloads "dema-rc-bundle.tar.gz"
And the install script is executed with "./install-sc2.sh bundle.tar.gz"

One of the file names should be changed. 
Also: curl is nice, but it does not overwrite target file, so users are less likely to fully get an update or re-download by simply repeating commands.
one could use wget (that overwrite by default) like
```wget -O dema-rc-bundle.tar.gz https://gitlab.com/lucas.de.marchi/dema-rc/-/jobs/artifacts/master/raw/build/dema-rc-bundle.tar.gz?job=bundle-sc2```
or just add ```rm install-sc2.sh dema-rc-bundle.tar.g```  as first command, to make it foolproof :)

**Comment by lucasdemarchi** [comment]
> And the install script is executed with "./install-sc2.sh bundle.tar.gz"

I'd prefer to fix in the docs and leave the file as is.

> Also: curl is nice, but it does not overwrite target file, so users are less likely to fully get an update or re-download by simply repeating commands.
> one could use wget (that overwrite by default) like
> `wget -O dema-rc-bundle.tar.gz https://gitlab.com/lucas.de.marchi/dema-rc/-/jobs/artifacts/master/raw/build/dema-rc-bundle.tar.gz?job=bundle-sc2`
> or just add `rm install-sc2.sh dema-rc-bundle.tar.g` as first command, to make it foolproof :)

well... the current options used don't override. We could make it overwrite by using `-o` option. Both curl and wget would work for me. Can you create a PR to change it?

**Comment by AndKe** [comment]
Can I git clone, then edit the docs/install-ardupilot.md file directly and make a PR for it - or is this file auto-generated by some other editing tools I am supposed to use?

**Comment by lucasdemarchi** [comment]
Yes, that should work

**Comment by AndKe** [comment]
The documentation on https://lucasdemarchi.github.io/ is 404 now?
Did you move it?

**Comment by lucasdemarchi** [comment]
It's on ardupilot now. https://lucasdemarchi.github.io/dema-rc/

**Pull request merged**
